### ISSUE TITLE
Rails 7 Won't allow Settings inside initilaizers

### ISSUE THREAD

**Issue by tjhanley** [ElMassimo/better_settings#4]
### Description 📖

When upgrading to Rails 7 from Rails 6.1 I am unable to load `Settings` in initializers.

### Reproduction 🐞
<details>

```bash
bundle exec rake zeitwerk:check 
rake aborted!
NameError: uninitialized constant Settings
Did you mean?  String
/core/config/initializers/sidekiq.rb:10:in `<main>'
```

```ruby 
# config/initilizers/sidekiq.rb
...
redis_host_string = "#{Settings.redis.scheme}://#{Settings.redis.host}:#{Settings.redis.port}/#{Settings.redis.sidekiq_db}"
```
</details>

### Logs 📜

_Error output or similar when the error occurs:_

<details>
<summary>Output</summary>

```
bundle exec rake zeitwerk:check                                                                        ─╯
rake aborted!
NameError: uninitialized constant Settings
Did you mean?  String
/Users/tom/Workspace/core/config/initializers/sidekiq.rb:10:in `<main>'
/Users/tom/Workspace/core/config/environment.rb:5:in `<main>'
/Users/tom/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/Users/tom/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Tasks: TOP => zeitwerk:check => environment
(See full trace by running task with --trace)
```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by ElMassimo** [comment]
Hi Thomas! @tjhanley

`Settings` is a class you defined (this library provides the `BetterSettings` class), so I'd check if this is caused by switching from the classic autoloader to Zeitwerk.

Make sure to place `Settings` in a file that is auto-loaded by default, such as `app/models/settings.rb`.

If that still doesn't work, you might want to manually require the file where you define your settings, but it shouldn't be necessary.

If you share an example repo that replicates the problem, I can take a look.

**Comment by tjhanley** [comment]
I finally got around to this.

Requiring the `settings.rb` file passes the Zeitwerk checks now. 

Thanks
